### ISSUE TITLE
Support multiple key encryption?

### ISSUE THREAD

**Issue by pwFoo** [Naeemo/cryptico#2]
Is it possible to support encryption with multiple keys to send messages to multiple users?

**Comment by Naeemo** [comment]
I don't think I quite understand your question, allow me guess here:
This is mainly for browser usage, so if you need to send multiple encrypted message to other users(browsers), it will has to be sent to the __server__ first.

**Comment by pwFoo** [comment]
I think I need this one
https://github.com/juhoen/hybrid-crypto-js
